apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: vsphere-pv-csi.community.tanzu.vmware.com.2.4.1
spec:
  refName: vsphere-pv-csi.community.tanzu.vmware.com
  version: 2.4.1
  releaseNotes: "vsphere-csi 2.4.1 https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v2.4.1"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/vsphere-pv-csi@sha256:cb05deb31bab55f92e7327ab22169d573444b9ccc1b07b0e448e28bd5bd48cf1
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
